apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openhab-helm-chart.fullname" . }}
  labels:
    {{- include "openhab-helm-chart.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "openhab-helm-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "openhab-helm-chart.selectorLabels" . | nindent 8 }}
    spec:
      {{ if .Values.nodeSelector.active }}
      nodeSelector:
        kubernetes.io/hostname: {{ .Values.nodeSelector.hostname }}
      {{ end }}
#      hostNetwork: true
      containers:
      - image: openhab/openhab:3.1.0
        name: openhab
        env:
        - name: USER_ID
          value: "9999"
        - name: GROUP_ID
          value: "9999"
        ports:
        - containerPort: 8080
        - containerPort: 8443
        - containerPort: 8001
        - containerPort: 8101
        - containerPort: 1900
        - containerPort: 9124
        resources: {}
        tty: true
        volumeMounts:
        - name: openhabconf
          mountPath: /openhab/conf
          subPath: conf
        - name: openhabuserdata
          mountPath: /openhab/userdata
          subPath: userdata
        - name: localtime
          mountPath: /etc/localtime
          readOnly: true
        - name: timezone
          mountPath: /etc/timezone
          readOnly: true
      restartPolicy: Always
      volumes:
      - name: openhabconf
        persistentVolumeClaim:
          claimName: openhab-conf-pvc
      - name: openhabuserdata
        persistentVolumeClaim:
          claimName: openhab-userdata-pvc
      - name: localtime
        hostPath:
          path: /etc/localtime
      - name: timezone
        hostPath:
          path: /etc/timezone
status: {}
