apiVersion: v1
kind: Service
metadata:
  name: {{ include "openhab-helm-chart.fullname" . }}
  labels:
    {{- include "openhab-helm-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: "8888"
      port: 8888
      targetPort: 8080
    - name: "8443"
      port: 8443
      targetPort: 8443
    - name: "8101"
      port: 8101
      targetPort: 8101
    - name: "8001"
      port: 8001
      targetPort: 8001
    - name: "9123"
      port: 9123
      targetPort: 9123
    - name: "9124"
      port: 9124
      targetPort: 9124
    - name: "9125"
      port: 9125
      targetPort: 9125
    - name: "9126"
      port: 9126
      targetPort: 9126
  selector:
    {{- include "openhab-helm-chart.selectorLabels" . | nindent 4 }}

